export enum TyneRoutes {
    Init               = "inicio",
    InitTyne           = "inicio-tyne",
    CommensalRegister  = "registro-comensales",
    Privacity          = "privacidad",
    Refund             = "reembolso",
    FrecuentQuestion   = "preguntas-frecuentes",
    Support            = "soporte",
    LocalProfile       = "perfil-local",
    ClientProfile      = "perfil-cliente",
    LocalResult        = "resultados-locales",
    Menu               = "menu",
    TableReservation   = "reserva-mesa",
    FavouriteLocal     = "locales-favoritos",
    EditReservation    = "edicion-reserva",
    BuyConfirmation    = "confirmacion-compra",
    CancelReservation  = "cancelacion-reserva",
    QualifyExperience  = "calificar-experiencia",
    NotFound           = "pagina-no-encontrada"
}