export enum TyneRoutes {
  Home = "inicio",
  InitTyne = "inicio-tyne",
  BusinessRegister = "registro-comensales",
  BusinessProfile = "perfil-local",
  BusinessSearchResults = "resultados-locales",
  BusinessEditMenu = "menu",
  BusinessDetail = "detalle-local",
  ClientProfile = "perfil-cliente",
  ClientMenu = "detalle-menu",
  Privacity = "privacidad",
  Refund = "reembolso",
  FrecuentQuestion = "preguntas-frecuentes",
  Support = "soporte",
  TableReservation = "reserva-mesa",
  FavouriteLocal = "locales-favoritos",
  EditReservation = "edicion-reserva",
  BuyConfirmation = "confirmacion-compra",
  CancelReservation = "cancelacion-reserva",
  QualifyExperience = "calificar-experiencia",
  NotFound = "pagina-no-encontrada",
  IncomeDetails = "caja-virtual",
  Opinions = "opiniones",
  BusinessCancelations = "cancelaciones",
}
